using System;using System.IO;using System.IO.Compression;using System.Linq;using System.Collections.Generic;using System.Runtime.InteropServices;using Microsoft.Win32.SafeHandles;using SO4KoreanPatcher;
internal static class Tests
{
 static int checks;static string project,work,encoder;static void Check(bool value,string why){checks++;if(!value)throw new Exception(why);}
 static void Reject(Action a,string why){bool failed=false;try{a();}catch(IOException){failed=true;}catch(InvalidDataException){failed=true;}Check(failed,why);}
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool DeviceIoControl(SafeFileHandle file,uint code,IntPtr input,int inputSize,IntPtr output,int outputSize,out int returned,IntPtr overlapped);
 static void Main(string[] args){try{project=Path.GetFullPath(args[0]);work=Path.GetFullPath(args[1]);Directory.CreateDirectory(work);encoder=Path.Combine(Path.GetDirectoryName(project),"tools/xdelta3-3.2.1/xdelta3-3.2.1-windows-x86_64/xdelta3.exe");if(args.Length>2&&args[2]=="full")Full(args[3]);else Transactions();Console.WriteLine("PASS "+checks+" assertions");}catch(Exception e){Console.Error.WriteLine(e);Environment.ExitCode=1;}}
 static void Add(ZipArchive z,string name,byte[] bytes){using(var s=z.CreateEntry(name).Open())s.Write(bytes,0,bytes.Length);}
 sealed class Fixture{internal string Root,Data,Hash;internal byte[] Zero,One;internal Manifest Plan;}
 static Fixture Make(string name,int revision=0)
 {
  string root=Path.Combine(work,name+"-"+Guid.NewGuid().ToString("N").Substring(0,8));Directory.CreateDirectory(root);var b0=new byte[8192];var b1=new byte[4096];var rng=new Random(619);rng.NextBytes(b0);rng.NextBytes(b1);
  File.WriteAllBytes(Path.Combine(root,"0000.bin"),b0);File.WriteAllBytes(Path.Combine(root,"0001.bin"),b1);var exe=new byte[]{1,2,3,4};File.WriteAllBytes(Path.Combine(root,"StarOceanTheLastHope.exe"),exe);
  var ops=new List<Operation>();var patches=new List<byte[]>();
  for(int i=0;i<3;i++)
  {
   string file=i==2?"0001.bin":"0000.bin";int at=i==2?64+revision*128:4096;int length=i==2?512:4096;byte[] source=(i==2?b1:b0).Skip(at).Take(length).ToArray();byte[] target=i==1?Enumerable.Range(0,512+revision*16).Select(x=>(byte)((x+revision)%8)).ToArray():(byte[])source.Clone();if(i!=1)for(int x=22;x<70;x++)target[x]=(byte)(x*3+revision);
   string sourcePath=Path.Combine(root,"source"),targetPath=Path.Combine(root,"target"),deltaPath=Path.Combine(root,"delta");File.WriteAllBytes(sourcePath,source);File.WriteAllBytes(targetPath,target);
   DeltaTool.Run(encoder,"-e -f -D -a -A -S none -s "+DeltaTool.Q(sourcePath)+" "+DeltaTool.Q(targetPath)+" "+DeltaTool.Q(deltaPath));byte[] delta=File.ReadAllBytes(deltaPath);Check(Vcdiff.Decode(source,delta,target.Length).SequenceEqual(target),"Independent xdelta/C# interoperability");
   var cut=delta.Take(delta.Length-1).ToArray();Reject(()=>Vcdiff.Decode(source,cut,target.Length),"Truncated delta rejected");Reject(()=>Vcdiff.Decode(source,delta,target.Length-1),"Output bounds checked");var corrupt=(byte[])delta.Clone();corrupt[0]^=1;Reject(()=>Vcdiff.Decode(source,corrupt,target.Length),"Bad header rejected");
   patches.Add(delta);ops.Add(new Operation{label="test-"+i,sourceFile=file,sourceOffset=at,sourceLength=length,sourceHash=Storage.Hash(source),targetFile=file,targetOffset=i==1?8192:at,targetLength=target.Length,targetHash=Storage.Hash(target),stageFile="deltas/"+i.ToString("D4")+".xdelta",deltaHash=Storage.Hash(delta)});
  }
  var native=File.ReadAllBytes(Path.Combine(project,"Assets/wininet.dll"));var plan=new Manifest{schema=3,format="xdelta-ranges-v1",version="v261001",buildId=new string((char)('b'+revision),24),exeHash=Storage.Hash(exe),nativeHash=Storage.Hash(native),files=new[]{new FilePlan{name="0000.bin",sourceLength=b0.Length,targetLength=b0.Length+512+revision*16},new FilePlan{name="0001.bin",sourceLength=b1.Length,targetLength=b1.Length}},operations=ops.ToArray()};
  string data=Path.Combine(root,"test.data");using(var z=ZipFile.Open(data,ZipArchiveMode.Create)){Add(z,"manifest.json",Storage.Utf8.GetBytes(Storage.Json(plan)));Add(z,"wininet.dll",native);for(int i=0;i<patches.Count;i++)Add(z,ops[i].stageFile,patches[i]);}
  return new Fixture{Root=root,Data=data,Hash=Storage.HashFile(data),Zero=b0,One=b1,Plan=plan};
 }
 static void Run(Fixture f,Action<int> fail=null,bool verify=false,List<int> progress=null){new PatchEngine(v=>{if(progress!=null)progress.Add(v);}){AfterWrite=fail}.Run(f.Root,f.Data,f.Hash,verify,f.Root);}
 static void Original(Fixture f){Check(File.ReadAllBytes(Path.Combine(f.Root,"0000.bin")).SequenceEqual(f.Zero),"BIN0 original restored");Check(File.ReadAllBytes(Path.Combine(f.Root,"0001.bin")).SequenceEqual(f.One),"BIN1 original restored");}
 static void Transactions()
 {
  var f=Make("normal");Run(f,null,true);Original(f);Check(!File.Exists(Path.Combine(f.Root,PatchEngine.RecordName)),"Verify is read-only");var progress=new List<int>();Run(f,null,false,progress);Check(progress.Last()==10000&&progress.Zip(progress.Skip(1),(a,b)=>b>a).All(x=>x),"Progress only rises");
  byte[] installed=File.ReadAllBytes(Path.Combine(f.Root,"0000.bin"));foreach(var o in f.Plan.operations)using(var s=File.OpenRead(Path.Combine(f.Root,o.targetFile)))Check(Storage.HashRange(s,o.targetOffset,o.targetLength,null)==o.targetHash,"Installed target verified");
  Check(installed.Take(4096).SequenceEqual(f.Zero.Take(4096)),"Untouched region exact");string record=Path.Combine(f.Root,PatchEngine.RecordName);var prior=Storage.Json<Journal>(File.ReadAllText(record));Run(f);Check(File.ReadAllBytes(Path.Combine(f.Root,"0000.bin")).SequenceEqual(installed),"Repatch restores then reapplies");Check(Storage.Json<Journal>(File.ReadAllText(record)).backupFolder!=prior.backupFolder,"Repatch creates new backup");
  var legacy=Storage.Json<Journal>(File.ReadAllText(record));legacy.schema=2;foreach(var o in legacy.operations){o.sourceOffset=o.targetOffset;o.sourceLength=o.targetOffset>=legacy.files.Single(x=>x.name==o.targetFile).sourceLength?0:o.targetLength;}
  Storage.AtomicJson(record,legacy);Run(f);Check(File.ReadAllBytes(Path.Combine(f.Root,"0000.bin")).SequenceEqual(installed),"Schema 2 backup migration");
  var fail=Make("write-failure");Reject(()=>Run(fail,i=>{if(i==1)throw new IOException("injected");}),"Injected write fault propagated");Original(fail);Check(!File.Exists(Path.Combine(fail.Root,"wininet.dll")),"No DLL after rollback");Run(fail);Check(Storage.Json<Journal>(File.ReadAllText(Path.Combine(fail.Root,PatchEngine.RecordName))).state=="installed","Retry after rollback");
  var damaged=Make("missing-backup");Run(damaged);string rec=Path.Combine(damaged.Root,PatchEngine.RecordName);var j=Storage.Json<Journal>(File.ReadAllText(rec));j.backups.Clear();Storage.AtomicJson(rec,j);byte[] saved=File.ReadAllBytes(Path.Combine(damaged.Root,"0000.bin"));Reject(()=>Run(damaged),"Incomplete backup rejected");Check(saved.SequenceEqual(File.ReadAllBytes(Path.Combine(damaged.Root,"0000.bin"))),"No writes before backup validation");
  var duplicate=Make("duplicate-backup");Run(duplicate);string dupRecord=Path.Combine(duplicate.Root,PatchEngine.RecordName);var dupJournal=Storage.Json<Journal>(File.ReadAllText(dupRecord));var first=dupJournal.backups[0];string duplicateEntry="9999.bin";File.Copy(Path.Combine(duplicate.Root,dupJournal.backupFolder,first.entry),Path.Combine(duplicate.Root,dupJournal.backupFolder,duplicateEntry));dupJournal.backups[1]=new Backup{file=first.file,offset=first.offset,length=first.length,hash=first.hash,entry=duplicateEntry};Storage.AtomicJson(dupRecord,dupJournal);byte[] duplicateBefore=File.ReadAllBytes(Path.Combine(duplicate.Root,"0000.bin"));Reject(()=>Run(duplicate),"Duplicate backup coverage rejected");Check(duplicateBefore.SequenceEqual(File.ReadAllBytes(Path.Combine(duplicate.Root,"0000.bin"))),"Duplicate backup rejected before writes");
  var restored=Make("externally-restored");Run(restored);File.WriteAllBytes(Path.Combine(restored.Root,"0000.bin"),restored.Zero);File.WriteAllBytes(Path.Combine(restored.Root,"0001.bin"),restored.One);File.Delete(Path.Combine(restored.Root,"wininet.dll"));string restoredRecord=Path.Combine(restored.Root,PatchEngine.RecordName);var stale=Storage.Json<Journal>(File.ReadAllText(restoredRecord));stale.schema=2;stale.backupFolder="SO4KoreanPatch.backup."+new string('d',32);Storage.AtomicJson(restoredRecord,stale);string recordHash=Storage.HashFile(restoredRecord),packedHash=Storage.HashFile(Path.Combine(restored.Root,"packed.txt"));Run(restored,null,true);Original(restored);Check(Storage.HashFile(restoredRecord)==recordHash&&Storage.HashFile(Path.Combine(restored.Root,"packed.txt"))==packedHash,"Externally restored verify leaves old journal and packed untouched");Run(restored);Check(Storage.Json<Journal>(File.ReadAllText(restoredRecord)).state=="installed","Externally restored original installs without old backup");foreach(var o in restored.Plan.operations)using(var s=File.OpenRead(Path.Combine(restored.Root,o.targetFile)))Check(Storage.HashRange(s,o.targetOffset,o.targetLength,null)==o.targetHash,"External restore final output exact");
  var foreign=Make("foreign-leftover");Run(foreign);File.WriteAllBytes(Path.Combine(foreign.Root,"0000.bin"),foreign.Zero);File.WriteAllBytes(Path.Combine(foreign.Root,"0001.bin"),foreign.One);File.WriteAllBytes(Path.Combine(foreign.Root,"wininet.dll"),new byte[]{7,8,9});Reject(()=>Run(foreign),"Unknown leftover not overwritten");Original(foreign);Check(File.ReadAllBytes(Path.Combine(foreign.Root,"wininet.dll")).SequenceEqual(new byte[]{7,8,9}),"Unknown DLL preserved");
  var wrong=Make("wrong-source");wrong.Zero[4120]^=1;File.WriteAllBytes(Path.Combine(wrong.Root,"0000.bin"),wrong.Zero);Reject(()=>Run(wrong),"Wrong source rejected");Original(wrong);
  var changed=Make("damaged-delta");changed.Hash=new string('0',64);Reject(()=>Run(changed),"Bad package hash rejected");Original(changed);
  var v1=Make("version-1",1);var v2=Make("version-2",2);var v3=Make("version-3",3);Run(v3);byte[] v3zero=File.ReadAllBytes(Path.Combine(v3.Root,"0000.bin")),v3one=File.ReadAllBytes(Path.Combine(v3.Root,"0001.bin"));Run(v1);
  Action<Fixture,string> apply=(version,root)=>new PatchEngine(null).Run(root,version.Data,version.Hash,false,null);
  Action<string> verifyV3=root=>{Check(File.ReadAllBytes(Path.Combine(root,"0000.bin")).SequenceEqual(v3zero),"Upgrade/reapply BIN0 equals clean latest install");Check(File.ReadAllBytes(Path.Combine(root,"0001.bin")).SequenceEqual(v3one),"Removed previous ranges restored and latest BIN1 exact");var record3=Storage.Json<Journal>(File.ReadAllText(Path.Combine(root,PatchEngine.RecordName)));Check(record3.buildId==v3.Plan.buildId&&record3.state=="installed","Latest version journal committed");foreach(var backup in record3.backups){byte[] originalBytes=backup.file=="0000.bin"?v3.Zero:v3.One;Check(File.ReadAllBytes(Path.Combine(root,record3.backupFolder,backup.entry)).SequenceEqual(originalBytes.Skip((int)backup.offset).Take((int)backup.length)),"Latest backup contains original bytes, not previously patched bytes");}};
  apply(v3,v1.Root);verifyV3(v1.Root);for(int repeat=0;repeat<3;repeat++){apply(v3,v1.Root);verifyV3(v1.Root);}
  var sequential=Make("sequential-upgrade",1);Run(sequential);apply(v2,sequential.Root);apply(v3,sequential.Root);verifyV3(sequential.Root);
  Storage.AtomicJson(Path.Combine(work,"version-upgrade-tests.json"),new{passed=true,sequential="v1 -> v2 -> v3",skip="v1 -> v3",sameVersionRepeats=3,latestFilesEqualCleanInstall=true,backupBytesEqualOriginal=true,changedRangesDifferBetweenVersions=true});
  Storage.AtomicJson(Path.Combine(work,"transaction-tests.json"),new{passed=true,assertions=checks});
 }
 static void Full(string game)
 {
  string root=Path.GetDirectoryName(project),fixture=Path.Combine(work,"customer-fixture");Directory.CreateDirectory(fixture);string data=Path.Combine(project,"bin/Release/SO4KoreanPatch.data");
  using(var pkg=new DeltaPackage(data,Storage.HashFile(data)))
  {
   var inputs=new Dictionary<string,FileStream>();var outputs=new Dictionary<string,FileStream>();try{
    foreach(var f in pkg.Plan.files){inputs[f.name]=File.OpenRead(Path.Combine(root,"backup_before_korean_patch/original_2026-07-11",f.name));var s=new FileStream(Path.Combine(fixture,f.name),FileMode.Create,FileAccess.ReadWrite,FileShare.None);int n;Check(DeviceIoControl(s.SafeFileHandle,0x900c4,IntPtr.Zero,0,IntPtr.Zero,0,out n,IntPtr.Zero),"Sparse test file");s.SetLength(f.sourceLength);outputs[f.name]=s;}
    foreach(var o in pkg.Plan.operations){var b=DeltaTool.Read(inputs[o.sourceFile],o.sourceOffset,o.sourceLength);Check(Storage.Hash(b)==o.sourceHash,"Actual original range");outputs[o.sourceFile].Position=o.sourceOffset;outputs[o.sourceFile].Write(b,0,b.Length);}
   }finally{foreach(var s in inputs.Values)s.Dispose();foreach(var s in outputs.Values)s.Dispose();}
   File.Copy(Path.Combine(game,"StarOceanTheLastHope.exe"),Path.Combine(fixture,"StarOceanTheLastHope.exe"),true);
   var values=new List<int>();var watch=System.Diagnostics.Stopwatch.StartNew();new PatchEngine(v=>{values.Add(v);}).Run(fixture,data,Storage.HashFile(data),false,null);
   foreach(var o in pkg.Plan.operations)using(var s=File.OpenRead(Path.Combine(fixture,o.targetFile)))Check(Storage.HashRange(s,o.targetOffset,o.targetLength,null)==o.targetHash,"Full baseline range identical");
   Check(Storage.HashFile(Path.Combine(fixture,"wininet.dll"))=="bf13768f254c83d6b79a44bac75086953904a9f30500f4ba6eb66b11d00f98ac","Exact known-good DLL");
   Check(values.Last()==10000&&values.Zip(values.Skip(1),(a,b)=>a<b).All(x=>x),"Full progress monotonic");
   Storage.AtomicJson(Path.Combine(work,"full-reference-test.json"),new{passed=true,operations=pkg.Plan.operations.Length,bytes=pkg.Plan.operations.Sum(o=>o.targetLength),assertions=checks,seconds=watch.Elapsed.TotalSeconds,fixture=fixture,nativeHash=pkg.Plan.nativeHash,fullGameExecuted=false,wholeBinHashed=false});Console.WriteLine("Full fixture equals reference in "+watch.Elapsed.TotalSeconds.ToString("F1")+" sec");
  }
 }
}
