using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Script.Serialization;

namespace SO4KoreanPatcher.Build
{
    internal static class BuildPackage
    {
        private static readonly Encoding Utf8 = new UTF8Encoding(false);
        private static string Hash(byte[] bytes) { using (var sha = SHA256.Create()) return BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-", "").ToLowerInvariant(); }
        private static void Entry(ZipArchive zip, string name, byte[] content)
        { var entry = zip.CreateEntry(name, CompressionLevel.Optimal); using (var s = entry.Open()) s.Write(content, 0, content.Length); }
        private static void Main(string[] args)
        {
            try { if (args.Length != 2) throw new ArgumentException("build|package project-directory"); string root = Path.GetFullPath(args[1]); if (args[0] == "build") Generate(root); else if (args[0] == "package") Package(root); else throw new ArgumentException("Unknown build action"); }
            catch (Exception e) { Console.Error.WriteLine(e.Message); Environment.ExitCode = 1; }
        }
        private static void Generate(string root)
        {
            string assets = Path.Combine(root, "Assets"), output = Path.Combine(root, "bin/Release"); Directory.CreateDirectory(output);
            var json = new JavaScriptSerializer { MaxJsonLength = 32 * 1024 * 1024 };
            var manifest = json.Deserialize<Dictionary<string, object>>(File.ReadAllText(Path.Combine(assets, "ResourceLocations.json"), Utf8));
            byte[] translations = File.ReadAllBytes(Path.Combine(assets, "Translations.jsonl")), font = File.ReadAllBytes(Path.Combine(assets, "NotoSansKR-Medium.ttf"));
            DateTime now = TimeZoneInfo.ConvertTime(DateTimeOffset.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Korea Standard Time")).DateTime;
            string version = "v" + now.ToString("yyMMdd"); manifest["version"] = version; manifest["builtAt"] = now.ToString("yyyy-MM-ddTHH:mm:ss.fffffff") + "+09:00"; manifest["author"] = "by Gideon"; manifest["fontHash"] = Hash(font);
            manifest["buildId"] = Hash(Utf8.GetBytes(json.Serialize(manifest) + Hash(translations))).Substring(0, 24);
            string temp = Path.Combine(output, "SO4KoreanPatch.data.tmp"), path = Path.Combine(output, "SO4KoreanPatch.data");
            using (var file = new FileStream(temp, FileMode.Create, FileAccess.ReadWrite, FileShare.None))
            using (var zip = new ZipArchive(file, ZipArchiveMode.Create))
            { Entry(zip, "manifest.json", Utf8.GetBytes(json.Serialize(manifest))); Entry(zip, "translations.jsonl", translations); Entry(zip, "NotoSansKR-Medium.ttf", font); }
            string dataHash = Hash(File.ReadAllBytes(temp)); if (File.Exists(path)) File.Replace(temp, path, null); else File.Move(temp, path);
            string generated = "// Generated by the C# build tool.\nusing System.Reflection;\n[assembly: AssemblyTitle(\"SO4KoreanPatcher\")]\n[assembly: AssemblyProduct(\"SO4KoreanPatcher\")]\n[assembly: AssemblyVersion(\"1.0.0.0\")]\n[assembly: AssemblyFileVersion(\"" + now.ToString("yyyy.M.d") + ".0\")]\n[assembly: AssemblyInformationalVersion(\"" + version + "\")]\nnamespace SO4KoreanPatcher { internal static class BuildInfo { internal const string Version = \"" + version + "\"; internal const string Id = \"" + manifest["buildId"] + "\"; internal const string DataHash = \"" + dataHash + "\"; } }\n";
            File.WriteAllText(Path.Combine(root, "src/Generated/BuildInfo.cs"), generated, Utf8);
            Console.WriteLine("C# resource package: " + version + ", " + new FileInfo(path).Length.ToString("N0") + " bytes");
        }
        private static void Package(string root)
        {
            string output = Path.Combine(root, "bin/Release"), data = Path.Combine(output, "SO4KoreanPatch.data"); string version;
            using (var z = ZipFile.OpenRead(data)) using (var s = new StreamReader(z.GetEntry("manifest.json").Open(), Utf8)) version = new JavaScriptSerializer().Deserialize<Dictionary<string, object>>(s.ReadToEnd())["version"].ToString();
            // Read documents directly into the ZIP. Even existing read-only copies in bin stay untouched.
            string path = Path.Combine(root, "bin/SO4KoreanPatcher-" + version + ".zip"), temp = path + ".tmp";
            var allowed = new List<string> { "SO4KoreanPatcher.exe", "SO4KoreanPatch.data", "README.md", "LICENSE" };
            if (File.Exists(Path.Combine(output, "SO4KoreanPatcher.exe.config"))) allowed.Add("SO4KoreanPatcher.exe.config");
            foreach (string folder in new[] { "docs", "samples" }) allowed.AddRange(Directory.GetFiles(Path.Combine(root, folder), "*", SearchOption.AllDirectories).Select(p => p.Substring(root.Length + 1)));
            using (var file = new FileStream(temp, FileMode.Create, FileAccess.ReadWrite, FileShare.None))
            using (var zip = new ZipArchive(file, ZipArchiveMode.Create))
                foreach (string name in allowed)
                {
                    bool document = name == "README.md" || name == "LICENSE" || name.StartsWith("docs" + Path.DirectorySeparatorChar, StringComparison.Ordinal) || name.StartsWith("samples" + Path.DirectorySeparatorChar, StringComparison.Ordinal);
                    Entry(zip, name.Replace('\\', '/'), File.ReadAllBytes(Path.Combine(document ? root : output, name)));
                }
            if (File.Exists(path)) File.Replace(temp, path, null); else File.Move(temp, path);
            Console.WriteLine("Release ZIP: " + new FileInfo(path).Length.ToString("N0") + " bytes");
        }
    }
}
